# Generated by Django 5.2.4 on 2025-08-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
    ]
